package hl7v27

// EHC_E10_INVOICE_PROCESSING_RESULTS_INFO - Group struct
type EHC_E10_INVOICE_PROCESSING_RESULTS_INFO struct {
	InvoiceProcessingResults IPR `hl7:"TAG=IPR"`
	NotesAndComments []NTE `hl7:"TAG=NTE;ATR=optional"`
	PayeeInformation PYE `hl7:"TAG=PYE"`
	Insurance IN1 `hl7:"TAG=IN1"`
	InsuranceAdditionalInformation IN2 `hl7:"TAG=IN2;ATR=optional"`
	InvoiceSegment IVC `hl7:"TAG=IVC"`
	ProductServiceSection []EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION `hl7:"GROUP"`
}

// EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION - Group struct
type EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION struct {
	ProductServiceSection PSS `hl7:"TAG=PSS"`
	ProductServiceGroup []EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP `hl7:"GROUP"`
}

// EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP - Group struct
type EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP struct {
	ProductServiceGroup PSG `hl7:"TAG=PSG"`
	ProductServiceLineInfo []EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PRODUCT_SERVICE_LINE_INFO `hl7:"GROUP"`
}

// EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PRODUCT_SERVICE_LINE_INFO - Group struct
type EHC_E10_INVOICE_PROCESSING_RESULTS_INFO_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PRODUCT_SERVICE_LINE_INFO struct {
	ProductServiceLineItem PSL `hl7:"TAG=PSL"`
	Adjustment []ADJ `hl7:"TAG=ADJ;ATR=optional"`
}

// EHC_E10 - Edit/Adjudication Results
// https://hl7-definition.caristix.com/v2/HL7v2.7/TriggerEvents/EHC_E10
type EHC_E10 struct {
	MessageHeader MSH `hl7:"TAG=MSH"`
	SoftwareSegment []SFT `hl7:"TAG=SFT;ATR=optional"`
	UserAuthenticationCredentialSegment []UAC `hl7:"TAG=UAC;ATR=optional"`
	MessageAcknowledgment MSA `hl7:"TAG=MSA"`
	Error []ERR `hl7:"TAG=ERR;ATR=optional"`
	InvoiceProcessingResultsInfo []EHC_E10_INVOICE_PROCESSING_RESULTS_INFO `hl7:"GROUP"`
}

