package hl7v271

// EHC_E01_INVOICE_INFORMATION - Group struct
type EHC_E01_INVOICE_INFORMATION struct {
	InvoiceSegment IVC `hl7:"TAG=IVC"`
	PayeeInformation PYE `hl7:"TAG=PYE;ATR=optional"`
	ContactData []CTD `hl7:"TAG=CTD;ATR=optional"`
	AuthorizationInformation AUT `hl7:"TAG=AUT;ATR=optional"`
	LocationIdentification []LOC `hl7:"TAG=LOC;ATR=optional"`
	Role []ROL `hl7:"TAG=ROL;ATR=optional"`
	ProductServiceSection []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION `hl7:"GROUP"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION struct {
	ProductServiceSection PSS `hl7:"TAG=PSS"`
	ProductServiceGroup []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP `hl7:"GROUP"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP struct {
	ProductServiceGroup PSG `hl7:"TAG=PSG"`
	LocationIdentification []LOC `hl7:"TAG=LOC;ATR=optional"`
	Role []ROL `hl7:"TAG=ROL;ATR=optional"`
	PatientInfo []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO `hl7:"GROUP;ATR=optional"`
	ProductServiceLineItem []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PRODUCT_SERVICE_LINE_ITEM `hl7:"GROUP"`
	Procedure []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PROCEDURE `hl7:"GROUP;ATR=optional"`
	InvoiceProcessing []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_INVOICE_PROCESSING `hl7:"GROUP;ATR=optional"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO struct {
	PatientIdentification PID `hl7:"TAG=PID"`
	PatientVisit PV1 `hl7:"TAG=PV1;ATR=optional"`
	PatientVisitAdditionalInformation PV2 `hl7:"TAG=PV2;ATR=optional"`
	Accident []ACC `hl7:"TAG=ACC;ATR=optional"`
	Insurance []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO_INSURANCE `hl7:"GROUP"`
	Diagnosis []EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO_DIAGNOSIS `hl7:"GROUP;ATR=optional"`
	ObservationResult []OBX `hl7:"TAG=OBX;ATR=optional"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO_INSURANCE - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO_INSURANCE struct {
	Insurance IN1 `hl7:"TAG=IN1"`
	InsuranceAdditionalInformation IN2 `hl7:"TAG=IN2;ATR=optional"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO_DIAGNOSIS - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PATIENT_INFO_DIAGNOSIS struct {
	Diagnosis DG1 `hl7:"TAG=DG1"`
	NotesAndComments []NTE `hl7:"TAG=NTE;ATR=optional"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PRODUCT_SERVICE_LINE_ITEM - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PRODUCT_SERVICE_LINE_ITEM struct {
	ProductServiceLineItem PSL `hl7:"TAG=PSL"`
	NotesAndComments []NTE `hl7:"TAG=NTE;ATR=optional"`
	Adjustment []ADJ `hl7:"TAG=ADJ;ATR=optional"`
	AuthorizationInformation AUT `hl7:"TAG=AUT;ATR=optional"`
	LocationIdentification []LOC `hl7:"TAG=LOC;ATR=optional"`
	Role []ROL `hl7:"TAG=ROL;ATR=optional"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PROCEDURE - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_PROCEDURE struct {
	Procedures PR1 `hl7:"TAG=PR1"`
	NotesAndComments []NTE `hl7:"TAG=NTE;ATR=optional"`
	Role []ROL `hl7:"TAG=ROL;ATR=optional"`
}

// EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_INVOICE_PROCESSING - Group struct
type EHC_E01_INVOICE_INFORMATION_PRODUCT_SERVICE_SECTION_PRODUCT_SERVICE_GROUP_INVOICE_PROCESSING struct {
	InvoiceProcessingResults IPR `hl7:"TAG=IPR"`
}

// EHC_E01 - Submit HealthCare Services Invoice
// https://hl7-definition.caristix.com/v2/HL7v2.7.1/TriggerEvents/EHC_E01
type EHC_E01 struct {
	MessageHeader MSH `hl7:"TAG=MSH"`
	SoftwareSegment []SFT `hl7:"TAG=SFT;ATR=optional"`
	UserAuthenticationCredentialSegment []UAC `hl7:"TAG=UAC;ATR=optional"`
	InvoiceInformation EHC_E01_INVOICE_INFORMATION `hl7:"GROUP"`
}

