package hl7v28

// ORL_O40_RESPONSE - Group struct
type ORL_O40_RESPONSE struct {
	Patient ORL_O40_RESPONSE_PATIENT `hl7:"GROUP;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT - Group struct
type ORL_O40_RESPONSE_PATIENT struct {
	PatientIdentification PID `hl7:"TAG=PID"`
	ParticipationInformation []PRT `hl7:"TAG=PRT;ATR=optional"`
	AccessRestriction []ARV `hl7:"TAG=ARV;ATR=optional"`
	Order []ORL_O40_RESPONSE_PATIENT_ORDER `hl7:"GROUP;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER struct {
	CommonOrder ORC `hl7:"TAG=ORC"`
	ParticipationInformation []PRT `hl7:"TAG=PRT;ATR=optional"`
	Timing []ORL_O40_RESPONSE_PATIENT_ORDER_TIMING `hl7:"GROUP;ATR=optional"`
	Observation_request ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST `hl7:"GROUP;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER_TIMING - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER_TIMING struct {
	TimingQuantity TQ1 `hl7:"TAG=TQ1"`
	TimingQuantityRelationship []TQ2 `hl7:"TAG=TQ2;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST struct {
	ObservationRequest OBR `hl7:"TAG=OBR"`
	ParticipationInformation []PRT `hl7:"TAG=PRT;ATR=optional"`
	Specimen_shipment []ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT `hl7:"GROUP;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT struct {
	Shipment SHP `hl7:"TAG=SHP"`
	Package []ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE `hl7:"GROUP"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE struct {
	ShipmentPackage PAC `hl7:"TAG=PAC"`
	Specimen_in_package []ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE_SPECIMEN_IN_PACKAGE `hl7:"GROUP;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE_SPECIMEN_IN_PACKAGE - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE_SPECIMEN_IN_PACKAGE struct {
	Specimen SPM `hl7:"TAG=SPM"`
	Specimen_container_in_package []ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE_SPECIMEN_IN_PACKAGE_SPECIMEN_CONTAINER_IN_PACKAGE `hl7:"GROUP;ATR=optional"`
}

// ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE_SPECIMEN_IN_PACKAGE_SPECIMEN_CONTAINER_IN_PACKAGE - Group struct
type ORL_O40_RESPONSE_PATIENT_ORDER_OBSERVATION_REQUEST_SPECIMEN_SHIPMENT_PACKAGE_SPECIMEN_IN_PACKAGE_SPECIMEN_CONTAINER_IN_PACKAGE struct {
	SpecimenContainerDetail SAC `hl7:"TAG=SAC"`
}

// ORL_O40 - Specimen Shipment Centric Laboratory Order Acknowledgment Message
// https://hl7-definition.caristix.com/v2/HL7v2.8/TriggerEvents/ORL_O40
type ORL_O40 struct {
	MessageHeader MSH `hl7:"TAG=MSH"`
	MessageAcknowledgment MSA `hl7:"TAG=MSA"`
	Error []ERR `hl7:"TAG=ERR;ATR=optional"`
	SoftwareSegment []SFT `hl7:"TAG=SFT;ATR=optional"`
	UserAuthenticationCredentialSegment UAC `hl7:"TAG=UAC;ATR=optional"`
	NotesAndComments []NTE `hl7:"TAG=NTE;ATR=optional"`
	Response ORL_O40_RESPONSE `hl7:"GROUP;ATR=optional"`
}

