package hl7v23

import "time"

// IN2 - Insurance additional info
// https://hl7-definition.caristix.com/v2/HL7v2.3/Segments/IN2
type IN2 struct {
	InsuredEmployeeID                    []CX        `hl7:"POS=2" json:"insuredEmployeeID,omitempty"`
	InsuredSSN                           string      `hl7:"POS=3" json:"insuredSSN,omitempty"`
	InsuredEmployerName                  []XCN       `hl7:"POS=4" json:"insuredEmployerName,omitempty"`
	EmployerInformationData              string      `hl7:"POS=5" json:"employerInformationData,omitempty"`
	MailClaimParty                       []string    `hl7:"POS=6" json:"mailClaimParty,omitempty"`
	MedicareHealthInsCardNumber          string      `hl7:"POS=7" json:"medicareHealthInsCardNumber,omitempty"`
	MedicalCaseName                      []XPN       `hl7:"POS=8" json:"medicalCaseName,omitempty"`
	MedicalCaseNumber                    string      `hl7:"POS=9" json:"medicalCaseNumber,omitempty"`
	ChampusSponsorName                   []XPN       `hl7:"POS=10" json:"champusSponsorName,omitempty"`
	ChampusID                            string      `hl7:"POS=11" json:"champusID,omitempty"`
	DependentOfChampusRecipient          CE          `hl7:"POS=12" json:"dependentOfChampusRecipient,omitempty"`
	ChampusOrganization                  string      `hl7:"POS=13" json:"champusOrganization,omitempty"`
	ChampusStation                       string      `hl7:"POS=14" json:"champusStation,omitempty"`
	ChampusService                       string      `hl7:"POS=15" json:"champusService,omitempty"`
	ChampusRank                          string      `hl7:"POS=16" json:"champusRank,omitempty"`
	ChampusStatus                        string      `hl7:"POS=17" json:"champusStatus,omitempty"`
	ChampusRetireDate                    time.Time   `hl7:"POS=18;ATR=date" json:"champusRetireDate,omitempty"`
	ChampusNonAvailCertOnFile            string      `hl7:"POS=19" json:"champusNonAvailCertOnFile,omitempty"`
	BabyCoverage                         string      `hl7:"POS=20" json:"babyCoverage,omitempty"`
	CombineBabyBill                      string      `hl7:"POS=21" json:"combineBabyBill,omitempty"`
	BloodDeductible                      string      `hl7:"POS=22" json:"bloodDeductible,omitempty"`
	SpecialCoverageApprovalName          []XPN       `hl7:"POS=23" json:"specialCoverageApprovalName,omitempty"`
	SpecialCoverageApprovalTitle         string      `hl7:"POS=24" json:"specialCoverageApprovalTitle,omitempty"`
	NonCoveredInsuranceCode              []string    `hl7:"POS=25" json:"nonCoveredInsuranceCode,omitempty"`
	PayorID                              []CX        `hl7:"POS=26" json:"payorID,omitempty"`
	PayorSubscriberID                    []CX        `hl7:"POS=27" json:"payorSubscriberID,omitempty"`
	EligibilitySource                    string      `hl7:"POS=28" json:"eligibilitySource,omitempty"`
	RoomCoverageType                     []CM_RMC    `hl7:"POS=29" json:"roomCoverageType,omitempty"`
	PolicyTypeAmount                     []CM_PTA    `hl7:"POS=30" json:"policyTypeAmount,omitempty"`
	DailyDeductible                      CM_DDI      `hl7:"POS=31" json:"dailyDeductible,omitempty"`
	LivingDependency                     string      `hl7:"POS=32" json:"livingDependency,omitempty"`
	AmbulatoryStatus                     string      `hl7:"POS=33" json:"ambulatoryStatus,omitempty"`
	Citizenship                          string      `hl7:"POS=34" json:"citizenship,omitempty"`
	PrimaryLanguage                      CE          `hl7:"POS=35" json:"primaryLanguage,omitempty"`
	LivingArrangement                    string      `hl7:"POS=36" json:"livingArrangement,omitempty"`
	PublicityIndicator                   CE          `hl7:"POS=37" json:"publicityIndicator,omitempty"`
	ProtectionIndicator                  string      `hl7:"POS=38" json:"protectionIndicator,omitempty"`
	StudentIndicator                     string      `hl7:"POS=39" json:"studentIndicator,omitempty"`
	Religion                             string      `hl7:"POS=40" json:"religion,omitempty"`
	MothersMaidenName                    XPN         `hl7:"POS=41" json:"mothersMaidenName,omitempty"`
	NationalityCode                      CE          `hl7:"POS=42" json:"nationalityCode,omitempty"`
	EthnicGroup                          string      `hl7:"POS=43" json:"ethnicGroup,omitempty"`
	MaritalStatus                        []string    `hl7:"POS=44" json:"maritalStatus,omitempty"`
	EmploymentStartDate                  time.Time   `hl7:"POS=45;ATR=date" json:"employmentStartDate,omitempty"`
	EmploymentStopDate                   time.Time   `hl7:"POS=46;ATR=date" json:"employmentStopDate,omitempty"`
	JobTitle                             string      `hl7:"POS=47" json:"jobTitle,omitempty"`
	JobCode                              JCC         `hl7:"POS=48" json:"jobCode,omitempty"`
	JobStatus                            string      `hl7:"POS=49" json:"jobStatus,omitempty"`
	EmployerContactPersonName            []XPN       `hl7:"POS=50" json:"employerContactPersonName,omitempty"`
	EmployerContactPersonPhone           []XTN       `hl7:"POS=51" json:"employerContactPersonPhone,omitempty"`
	EmployerContactReason                string      `hl7:"POS=52" json:"employerContactReason,omitempty"`
	InsuredContactPersonName             []XPN       `hl7:"POS=53" json:"insuredContactPersonName,omitempty"`
	InsuredContactPersonTelephone        []XTN       `hl7:"POS=54" json:"insuredContactPersonTelephone,omitempty"`
	InsuredContactPersonReason           []string    `hl7:"POS=55" json:"insuredContactPersonReason,omitempty"`
	RelationshipToThePatientStartDate    time.Time   `hl7:"POS=56;ATR=date" json:"relationshipToThePatientStartDate,omitempty"`
	RelationshipToThePatientStopDate     []time.Time `hl7:"POS=57;ATR=date" json:"relationshipToThePatientStopDate,omitempty"`
	InsuranceCompanyContactReason        string      `hl7:"POS=58" json:"insuranceCompanyContactReason,omitempty"`
	InsuranceCompanyContactPhone         XTN         `hl7:"POS=59" json:"insuranceCompanyContactPhone,omitempty"`
	PolicyScope                          string      `hl7:"POS=60" json:"policyScope,omitempty"`
	PolicySource                         string      `hl7:"POS=61" json:"policySource,omitempty"`
	PatientMemberNumber                  CX          `hl7:"POS=62" json:"patientMemberNumber,omitempty"`
	GuarantorRelationshipToInsured       string      `hl7:"POS=63" json:"guarantorRelationshipToInsured,omitempty"`
	InsuredsTelephoneNumberHome          []XTN       `hl7:"POS=64" json:"insuredsTelephoneNumberHome,omitempty"`
	InsuredEmployerTelephoneNumber       []XTN       `hl7:"POS=65" json:"insuredEmployerTelephoneNumber,omitempty"`
	MilitaryHandicappedProgram           CE          `hl7:"POS=66" json:"militaryHandicappedProgram,omitempty"`
	SuspendFlag                          string      `hl7:"POS=67" json:"suspendFlag,omitempty"`
	CopayLimitFlag                       string      `hl7:"POS=68" json:"copayLimitFlag,omitempty"`
	StoplossLimitFlag                    string      `hl7:"POS=69" json:"stoplossLimitFlag,omitempty"`
	InsuredOrganizationNameAndID         []XON       `hl7:"POS=70" json:"insuredOrganizationNameAndID,omitempty"`
	InsuredEmployerOrganizationNameAndID []XON       `hl7:"POS=71" json:"insuredEmployerOrganizationNameAndID,omitempty"`
	Race                                 string      `hl7:"POS=72" json:"race,omitempty"`
	PatientRelationshipToInsured         CE          `hl7:"POS=73" json:"patientRelationshipToInsured,omitempty"`
}
